# Generated by Django 5.0.1 on 2024-02-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encoding',
            name='password',
        ),
        migrations.AddField(
            model_name='decoding',
            name='message',
            field=models.TextField(default=''),
        ),
    ]
