# Generated by Django 5.0.1 on 2024-02-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0003_alter_decoding_image_alter_encoding_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoding',
            name='image',
            field=models.ImageField(upload_to='decodings/'),
        ),
        migrations.AlterField(
            model_name='encoding',
            name='image',
            field=models.ImageField(upload_to='encodings/'),
        ),
    ]
