# Generated by Django 5.0.1 on 2024-02-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0005_decoding_type_encoding_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='encoding',
            name='password_used',
            field=models.BooleanField(default=False),
        ),
    ]
