# Generated by Django 5.0.1 on 2024-02-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steganography', '0006_encoding_password_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encoding',
            name='password_used',
        ),
    ]
